comment: false

language: R

sudo: false

cache: packages

after_success:

- Rscript -e 'covr::codecov()'


coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true


codecov:
  token: f5ef932d-5b1e-4b30-acc4-064e78838d61

- name: Test coverage
  run: Rscript -e 'covr::codecov()'


